# Generated by Django 5.0.8 on 2024-08-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('sno', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('mail', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
